### ISSUE TITLE
DAC/King of the Hill changes

### ISSUE THREAD

**Issue by JeffBobbo** [redeclipse/base#418]
Split up DAC into DAC and KOTH to allow for new mutators.

http://redeclipse.net/forum/viewtopic.php?f=4&t=830

**Comment by qreeves** [comment]
Recent development has opted to reduce the number of gamemode/mutator options rather than increase them. This is in conjunction with the overall opinion that KOTH isn't widely adopted as a selected game type and the poor ability to defend in what is primarily an offensive oriented arena shooter. As a result, I'm closing this issue.
