### ISSUE TITLE
It's (nearly) impossible to strike down with sword in third person.

### ISSUE THREAD

**Issue by JeffBobbo** [redeclipse/base#435]
Can easily be tested by standing on a bot (with botspeed 0), you can get a hit with both sword1 and sword2, but it's really hard to do, in first person there are no problems.

**Comment by qreeves** [comment]
This is mostly because it is based on the animations, and in third person those animations are different. There was an effort to fix the animations before (was Unnamed that did it I think?), but I guess there is only so much that can be done there due to the camera angle as well. I'll leave the issue here, but it is unlikely it will get fixed quickly, if at all. This is a *first* person shooter, and that is prioritised above all else.

**Comment by Dziq84** [comment]
I changed animation of tpp sword1 and its a bit better I think,   I can stil tweak that one if necessary.  Sword2 anim is nice done so I not touched that one, I can only suggest one thing:
  -distinquish 'trace' vars to use different values for FPP and TPP views
Currently swordtrace1 and 2 value is a bit too big,  while in TPP - too low

**Comment by SniperGoth** [comment]
It also has something to do with the way the camera focuses.
If you are  very close to a enemy, with the crosshair on them, the player character will naturally rotate his body torwards where the crosshair is, and so, make the sword2 kind of hard to use effectively.
Screenshots below : 
![20190513113741](https://user-images.githubusercontent.com/24359960/57630298-be8b4d80-7573-11e9-8258-f424093afa5e.png)
![20190513113744](https://user-images.githubusercontent.com/24359960/57630299-be8b4d80-7573-11e9-940e-3c28c223c790.png)
![20190513113750](https://user-images.githubusercontent.com/24359960/57630300-be8b4d80-7573-11e9-9932-c71baf5ee60f.png)
![20190513113814](https://user-images.githubusercontent.com/24359960/57630309-c0eda780-7573-11e9-9b2d-be60ef02dc92.png)
So, i'd try to make the sword trace different for the third person view, like dziq suggested, to balance things out and see if it works.
