### ISSUE TITLE
Red Eclipse does not follow default sound output on Windows

### ISSUE THREAD

**Issue by acerspyro** [redeclipse/base#651]
Multiple issues here:

To start off, when the default audio output is changed on Windows, the game does not follow and keeps using the previous audio source. Not too bad of a bug so far.

But that also means that if the audio sink disappears (e.g. I disconnect my Bluetooth headphones or my bluetooth speaker), the sound disappears completely, and only a game restart can bring it back. Also, the game seems to hang upon shutting down, probably due to trying to close a non-existing audio sink. Not cool.

The best solution would be to listen for a default audio output change in Windows, and switch to it automagically.

**Comment by qreeves** [comment]
I don't think that is even possible with SDL. You may be able to select a specific audio device, but monitoring it and recovering from a faulty state would be SDL's job.

**Comment by acerspyro** [comment]
Can we interact with the Windows sound API directly and work around the issue until SDL releases a fix?

**Comment by qreeves** [comment]
Not really, there's a reason SDL exists.

**Comment by acerspyro** [comment]
Close the issue and re-open it later or are we going to do something about it?

**Comment by graphitemaster** [comment]
Redeclipse is still using the legacy SDL 1.2 sound API which is provided in SDL2. That is it uses `SDL_OpenAudio` Which always assumes the first device it finds. It used to be in the earlier versions of SDL2 that it would be the default system device. This is no longer true since SDL 2.0.5. The actual library functionality that _should_ be used is `SDL_OpenAudioDevice`.

**Comment by graphitemaster** [comment]
That functionality allows monitoring of audio backends disappearing and allows you to reacquire contexts. As well as some other neat things.

**Comment by qreeves** [comment]
Ugh, there's a legacy API.. I didn't realise it hadn't been properly ported.

**Comment by graphitemaster** [comment]
I should provide more information here since my previous comment isn't entierly accurate. Redeclipse, like Tesseract use SDL_mixer, which uses `Mix_OpenAudio`. This is equivlant to calling the newer `Mix_OpenAudioDevice` with a `NULL` device. This behavior is mirrored in plain SDL with the addition of `SDL_OpenAudioDevice` in 2.0.5 but `SDL_OpenAudio` still being available for legacy. The difference is the `OpenAudioDevice` varients permit you to open an audio device by name. These names can be queried with `SDL_GetAudioDeviceName` which expects an index, the number of audio devices can be queried with `SDL_GetNumAudioDevices(0)`. So what does this have to do with Redeclipse? Well since SDL 2.0.5, SDL has added a new event type `SDL_AudioDeviceEvent` which is accessible off the `SDL_Event` struct via `adevice`. SDL 2.0.5 adds support for dynamic audio devices with the new events `SDL_AUDIODEVICEADDED and SDL_AUDIODEVICEREMOVED` which can be determined via the `type` field of that `SDL_AudioDeviceEvent` structure, that structure also contains a `which` field, which is an integer index for the device that was added or removed. Redeclipse does not handle the situation when the device in use is removed and then something else is added or the same device is readded (the index is not guranteed to be the same.) This is relatively trivial to support however, we just need to modify the way the sound subsystem is initialized to use `Mix_OpenAudioDevice` with some user-passed string for the device name, leaving it to `NULL` by default, and storing the current audio device index associated with that, when that shows up in an `SDL_AUDIODEVICEREMOVED` event just shutdown the sound system completely, then when we see an `SDL_AUDIODEVICEADDED` event, grab that index, call `SDL_GetAudioDeviceName` and pass that string back into the audio system and reinitialize it.

**Comment by graphitemaster** [comment]
I'm considering this a higher priority because systems, such as mine have very dynamic audio configurations, Pulseaudio sinks to switch between output devices cause these events to trigger in all SDL applications and some of them just plain lock up. Simply plugging in a headset and having it auto switch to playback over headphones other than speakers causes Redeclipse to dead lock in SDL_mixer.

**Comment by graphitemaster** [comment]
Tesseract has similar problems @lsalzman I can provide a patch if needed

**Comment by q009** [comment]
Not an issue after OpenAL implementation
