### ISSUE TITLE
Tesseract shadow resolution and map size problems

### ISSUE THREAD

**Issue by Hevedy** [redeclipse/base#819]
I notice the original Tesseract have a problem with the realtime shadow, seems like if you make a bigger map or based in the level size the shadows get worst and worst quality as bigger the map is worst quality the shadows have. Just wanted to post here if no one noticed it yet.

As I notice the game/engine are begin ported or updated.

**Comment by qreeves** [comment]
Real time shadows use an off screen texture at a set size, if the size of the texture overflows then it will reduce the resolution of the shadows in order to display what needs to be drawn. You can improve this by increasing the various shadow variables to higher values.

The defaults are made for an average computer, and it is (and always has been) discouraged to make large expansive maps in this engine (as well as Cube 2 itself).

**Comment by Hevedy** [comment]
Well yeah I don't even tried to make a big map, but a map of some of the Cube 2 sized ones <med size> and the result was really bad <with settings at max> as even worst quality than 2007 games realtime shadows.<Looks probably even x4 times more pixelated than Cube 2 ones> So idk probably could be interesting other method or no idea waht

**Comment by SniperGoth** [comment]
Just to add to the conversation (it's sort of related anyway): If you happen to trigger the sunlight bug when dealing with bigger maps, you can solve it by using /glineardepth 1 (it's 0 by default).
As for pixelated shadows, try to change smzise to a bigger number and maybe smfilter, as they control the shadow resolution/filter and lets see if that solves it ^^

**Comment by Hevedy** [comment]
Didn't tried the first coded one but the shadowmap size and the filter was at max and the quality was really reall bad

**Comment by Hevedy** [comment]
All max settings: <Only filter disabled to notice better the pixel size>

Size 12: ![tesseract_12](https://user-images.githubusercontent.com/3521442/38730095-87a75ae2-3f15-11e8-9230-049ac9cbddb7.jpg)
Size 16: ![tesseract_16](https://user-images.githubusercontent.com/3521442/38730092-869c3d70-3f15-11e8-8268-0580b02e2cc0.jpg)

Plus at 16 or 15 even the TemporalAA have problems and move the whole image as if I was on fire, as you can see even the weapon have problems and the shadows are total different

**Comment by Hevedy** [comment]
Got a 970GTX and 16GB of Ram and a i7 working on UE4 each day. And got 400FPS on the demo maps of Tesseract running on Windows 7 Ult

**Comment by Dziq84** [comment]
there are few vars, that I changed locally (all in autoexec because seems these are never saved in config.cfg) to have better visuals:
/csmmaxsize 1024 (default ~750)   working for me without any issues even with these:
/csmsplits 8 (default 3) - nicer shadows from sunlight
/csmfarplane 4096 (default 1024) - shadows are drawed more far away
/rhfarplane 8192 (defailt 1024) -GI (seems so) do not popup even on bigger maps

with these I realised only 1 or 2 fps loss on my old hardware even on big maps (like 14 size)
Ideal sollution could be to use these vars based on current map size, bigger map - cranked up vars, smaller one - defaults or similiar. Now even on small maps, these shadows/GI popups are visible very clearly thus not looking good
