### ISSUE TITLE
Death material inaccuracy when jumping upwards

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/base#922]
Placing death material in some cases will not trigger death when the player collides with it. 
Here's one example i'm having trouble with; where you'd expect the player to die. However, if you impulse jump (double jump) in that example below, the player does indeed die. Seems like the player bounding box is in the wrong place? I'm not 100% certain, but seems like it will only trigger once the players waist collides with the material, rather than the head. 

![2019-09-29-061858_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/65826674-4226ac00-e281-11e9-88bb-305ba0fcc1ce.png)

EDIT: Video here to make it more clear: https://streamable.com/abyt1

**Comment by qreeves** [comment]
Currently, materials only check against the origin position (which is the feet). It is a known issue, and in the past it was determined that changing this behaviour would break too many race maps. Now that we're intentionally breaking backward compatibility, I'm going to mark this as a valid issue rather than close it.

**Comment by molexted** [comment]
a8408af9eb5fb4913ab32de15016d0b26436843d fixed this, closing.
