### ISSUE TITLE
[Meta-Tracker] GNU/Linux Mobile

### ISSUE THREAD

**Issue by WorryTheBirds12** [redeclipse/base#929]
## Basic Information

**Description**: Red Eclipse on GNU/Linux Mobile.
**Platforms**: TuxPhones has a list of them [here](https://tuxphones.com/all-linux-distributions-for-smartphones/)

## Solutions

One common 'theme'/'word' being used in other projects is the possibility of adaptive design:

![adaptive-layout](https://coinsh.red/u/adaptive.jpeg)

### Alternative designs

Developing a separate application for mobile devices.

## Additional context

Preferably, the applications would be using a tarball to start.
Therefore, it is easier to port to a variety of mobile OSes.

___________________________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=81857849)](https://www.bountysource.com/issues/81857849-meta-tracker-gnu-linux-mobile)

**Comment by qreeves** [comment]
Your issue is vague and doesn't contain enough information. Based on what little there is, I can only say there are no plans to support Red Eclipse on mobile devices, nor would such an effort be officially supported by the project due to the overwhelming task of maintaining and supporting such an endeavour.

I'm not sure if you or somebody else set up the 'red-eclipse' team on BountySource, but whoever did is erroneously claiming to be a representative of the project when they are not. As far as I can tell, this is a violation of section 4.2 of the BountySource Terms of Service.
