### ISSUE TITLE
Bloom

### ISSUE THREAD

**Issue by Minecraft-Beast101** [redeclipse/base#958]
Why isn't the crosshair the size of the weapon spread? That will make life much easier

**Comment by molexted** [comment]
Spread is a ratio, units of meters/meters; (distance spread divided by distance traveled) 
The crosshair displays a solid angle on the screen (area enclosed/area of screen).

The two only are identical for circumstances where the distance traveled is known relative to the screen's projected area, and this distance is very much not constant. The crosshair needs to also take into account projection distortion (larger FOVs will increase the projected solid area on the fixed screen size).

The RE2 HUD system does not support such complex crosshair compensation, and only the shotgun and plasma2 have any spread whatsoever. Because of that, it is not trivial to implement something like this in a useful manner.

If you are commenting on RE1.6, that version goes EOL in four days and will no longer be supported.
